const _ = require('node-validator')

module.exports = _.isObject()
  .withOptional('name', _.isString())
  .withOptional('description', _.isString())
  .withOptional('date_start', _.isDate())
  .withOptional('date_end', _.isDate())
  .withOptional('location', _.isString())
  .withOptional('photo', _.isString())
  .withOptional('private', _.isBoolean())
  .withOptional('organizers', _.isArray())
  .withOptional('participants', _.isArray())
  .withOptional('conversation', _.isObject())
  .withOptional('album', _.isObject())
  .withOptional('poll', _.isObject())
  .withOptional('ticketing', _.isObject())
  .withOptional('shoppingListOn', _.isBoolean())
  .withOptional('shoppingList', _.isArray())
  .withOptional('covoiturage', _.isBoolean())
  .withOptional('covoiturageList', _.isArray())
